name: currency_ar
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  go_router: ^14.0.2
  animations: ^2.0.8
  google_mlkit_entity_extraction: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
